# Default values for alertmanager-sns-forwarder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

region: US-WEST-2
arn: "arn:aws:sns:us-west-2:601471275036:"

replicaCount: 1

image:
  repository: objectrocket/alertmanager-sns-forwarder
  tag: v0.2
  pullPolicy: Always
  template: /tmp/template.tmpl

service:
  type: ClusterIP
  port: 9087


resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 0.5
    memory: 1Gi
  requests:
    cpu: 0.2
    memory: 0.5Gi

nodeSelector: {}

tolerations: []

affinity: {}
